<a href="https://colab.research.google.com/github/Vivekkotha544/The-PyTorch/blob/main/PyTorch_Day2_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# PyTorch Work Flow

# 1) Get data ready(trun into tensors) -> 2) Bulid or pick a pretrained Model -> 3) Fit the model to the data and make a prediction
# -> 4) Evaluate the Model -> 5) Improve through experimentation -> 6) Save and reload your trained model

# PyTorch Fundamentals

In [2]:
print("Hello I'm excited to learn PyTroch!")

Hello I'm excited to learn PyTroch!


In [2]:
!nvidia-smi

Fri Feb  9 15:00:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensor
## Creating Tensors

In [4]:
# scalar

scalar = torch.tensor(7) # Pytorch tensors are created using 'torch.tensor()'
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [ ]:
#Vector

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim #Dimension

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#Matrix

MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#Tensor

TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,34,5]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2, 34,  5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [ 2, 34,  5]])

In [17]:
#Tensor

TENSOR = torch.tensor([[[[1,2,3],
                         [3,6,9],
                         [2,34,5],
                         [22,24,25]]]])
TENSOR

tensor([[[[ 1,  2,  3],
          [ 3,  6,  9],
          [ 2, 34,  5],
          [22, 24, 25]]]])

In [18]:
TENSOR.ndim

4

In [20]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

### Random Tensor


In [21]:
#create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7088, 0.0818, 0.9332, 0.7840],
        [0.1349, 0.7500, 0.7150, 0.2405],
        [0.3691, 0.0508, 0.2073, 0.1700]])

In [22]:
random_tensor.ndim

2

In [25]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [27]:
#creating a tensor of all zeros

zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
#creating a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
# Creating a range of tensors and tensors-like

torch.range(0,10)

<ipython-input-31-e60fa1b8ea9d>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])