<a href="https://colab.research.google.com/github/Vivekkotha544/The-PyTorch/blob/main/PyTorch_Day3_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensor datatypes

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [3]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [3]:
float_32_tensor.dtype

torch.float32

In [4]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4973, 0.5820, 0.0744, 0.3208],
        [0.5978, 0.4786, 0.7917, 0.4063],
        [0.7585, 0.6786, 0.7703, 0.6488]])

In [5]:
some_tensor.size()

torch.Size([3, 4])

In [7]:
#Find out details about some tensor
print(some_tensor)
print(f"DataType of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.size}")
print(f"Device tensor is on:{some_tensor.device}")


tensor([[0.4973, 0.5820, 0.0744, 0.3208],
        [0.5978, 0.4786, 0.7917, 0.4063],
        [0.7585, 0.6786, 0.7703, 0.6488]])
DataType of tensor:torch.float32
Shape of tensor:<built-in method size of Tensor object at 0x7fd22d6bfb50>
Device tensor is on:cpu


### Manipulating Tensors(tensor Operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [9]:
#create a tensor [Addition]
tensor =torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [10]:
#Multiply
tensor*10

tensor([10, 20, 30])

In [11]:
#Subtract 10
tensor - 10

tensor([-9, -8, -7])

### Matrix Multiplication

The two ways of matrix multiplication are:

1. Element wise
2. Dot Product

In [20]:
# Element wise
print(tensor, "*", tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [21]:
#Dot product
torch.matmul(tensor,tensor)

tensor(14)

## Finding the min,max,mean,sum,etc(Tensor Aggregation)

In [23]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
#Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [25]:
#Find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [26]:
#Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [27]:
# Find the sum
torch.sum(x), x.sum

(tensor(450), <function Tensor.sum>)

In [28]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [29]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
#Find the position in the tensor that has the minimum value with argmin
x.argmin()

tensor(0)

In [31]:
x[0]

tensor(0)

In [32]:
x[3]

tensor(30)

In [33]:
x.argmax()

tensor(9)

In [34]:
x[9]

tensor(90)